name: name_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20  # Replace with the latest version if available
  shared_preferences: ^2.2.3
  english_words: ^4.0.0
  provider: ^6.0.0
  supabase_flutter: ^2.5.6
  timeago: ^3.1.0
  photo_view: ^0.15.0




dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/ZT230.png
      - assets/ZD411.png
      - assets/ZT410.png
      - assets/ZT411.png
      - assets/logo.jpg
      - assets/Computer.png
      - assets/MES.png
      - assets/Scanner.png
      - assets/comport1.png
      - assets/comport2.png
      - assets/comport3.png
      - assets/MESfreeze01.png
      - assets/MESfreeze02.png
      - assets/MESfreeze03.png
      - assets/MESfreeze04.png
      - assets/MESfreezewin1101.png
      - assets/MESfreezewin1102.png
      - assets/MESfreezewin1103.png
      - assets/icon.png
